### ISSUE TITLE
Problème lors du lancement top.php

### ISSUE THREAD

**Issue by LuffyyyffuL** [matthiasbosc/t412#11]
Bonjour,

Lorsque je lance la màj des top, j'ai le message suivant : 

Impossible de récupérer vos identifiants. Vérifiez que la constante T411::T411USER corresponde à votre pseudo T411.

La variable "CONST T411USER" dans le fichier "t412.class.php" contient bien mon nom d'utilisateur t411.

Une idée ? Merci :)

**Comment by matthiasbosc** [comment]
Il faudrait essayer de te connecter dans un onglet en navigation privée pour (re)générer un mot de passe en base.

**Comment by LuffyyyffuL** [comment]
Je viens de le faire mais j'ai toujours qu'un seul user en base, tjrs le meme message :/

**Comment by matthiasbosc** [comment]
Peux-tu me contacter par mail pour faire une série de tests ?
matthias@bosc.io

**Comment by jean-luc-56** [comment]
Bonjour;
Bravo, pour ce soft déjà découvert avant par rapport a mondedie, et qui fonctionnait très bien sur mon ancien serveur Debian Jessie; mais sur mon nouveau serveur, je suis passé sous Stretch qui ne va pas tarder à passer en stable et avec mariadb au lieu de mysql précédemment.
Tout fonctionne:
setup.php = OK
Création de compte + seedbox + téléchargement  + recherches = OK
Mais les top restent aussi désespérément vides.
lignes rentrées dans cron, qui les exécute bien, mais rien, à la main dans une console ssh:

root@serveur:~# /usr/bin/php /var/www/t412/cli/top.php
Impossible de récupérer vos identifiants. Vérifiez que la constante T411::T411USER corresponde à votre pseudo T411root@serveur:~#

Une idée...
Merci.

**Comment by matthiasbosc** [comment]
Bonjour, merci pour le retour ! ;)
Serait-il possible de me contacter par mail (matthias@bosc.io) pour essayer de trouver une solution ?
