### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by qrek** [matthiasbosc/t412#2]
Bonjour,
J'ai un petit problème sur l'adresse mondomaine.com/t412, j'ai une erreur nginx 404 not found, alors que j'ai exactement pris le vHost du tuto, et je n'arrive donc pas à accéder au login t412.

Merci d'avance !

**Comment by matthiasbosc** [comment]
Salut,

As-tu la possibilité de placer le site à la racine du domaine, ou dans un sous-domaine ? Je n'ai pas testé, mais le problème de redirection doit venir de ça.

Matthias.

**Comment by qrek** [comment]
Hello, 
Je l'ai placé à la racine du domaine dans /var/www/base
J'ai l'impression qu'il ne redirige pas vers la bonne page puis que j'ai des erreurs dans la console du genre "Not Authorized" et la redirection n'est pas la bonne.
Sauf que je ne sais absolument pas où changer ses paramètres :/

**Comment by matthiasbosc** [comment]
@qrek Peux-tu m'envoyer un mail ( matthias (dot) bosc (at) io ) en me précisant ton environnement (OS, version, version de nginx) et une copie de ton vhost nginx ?
Merci. :)

**Comment by qrek** [comment]
Yes, à tout de suite, merci !

**Comment by qrek** [comment]
Il me dit que ton adresse mail est incorrecte :/
