### ISSUE TITLE
Config nginx subdir t412 ?

### ISSUE THREAD

**Issue by LuffyyyffuL** [matthiasbosc/t412#3]
Bonjour,

J'essai d'afficher t412 avec nginx, mais je n'arrive pas à afficher la page correctement, je dois avoir un problème de rewrite.

Le dossier t412 est dans /var/www. J'arrive bien à afficher la page de login en tapant manuellement http://mon_domaine/t412/login, mais quand j'essai de me connecter, je n'a rien.

Voici ce que j'ai côté nginx : 

	location ^~ /t412 {
	
		root /var/www;
		
		include /etc/nginx/conf.d/php.conf;
		include /etc/nginx/conf.d/cache.conf;
		
		index index.html index.php;
        
		try_files $uri $uri/ =404;
              
		rewrite ^/details$|details/$|details/(.*)$ /t412/details.php?id=$1? last;
		rewrite ^/nfo$|nfo/$|nfo/(.*)$ /t412/nfo.php?id=$1? last;
		rewrite ^/download$|download/$|download/([0-9]*)$ /t412/download.php?id=$1? last;
		rewrite ^/download/([0-9]*)/$ /t412/download.php?id=$1? last;
		rewrite ^/dl$|dl/$|dl/(.*)$ /t412/dl.php?id=$1? last;
		rewrite ^/delete$|delete/$|delete/(.*)$ /t412/delete.php?id=$1? last;
		rewrite ^/login$|login/$ /t412/login.php last;
		rewrite ^/logout$|logout/$ /t412/logout.php last;
		rewrite ^/downloads$|downloads/$ /t412/downloads.php last;
		rewrite ^/seedbox$|seedbox/$ /t412/seedbox.php last;
		rewrite ^/suivi$|suivi/$ /t412/suivi.php last;
		rewrite ^/top/today$|top/today/$ /t412/top/today.php last;
		rewrite ^/top/week$|top/week/$ /t412/top/week.php last;
		rewrite ^/top/month$|top/month/$ /t412/top/month.php last;
	}

Si quelqu'un a la bonne config, je suis preneur, merci :)

**Comment by matthiasbosc** [comment]
@LuffyyyffuL Peux-tu m'envoyer un mail ( matthias (dot) bosc (at) io ) en me précisant ton environnement (OS, version, version de nginx) et une copie complète de ton vhost nginx ?
Merci. :)

**Comment by LuffyyyffuL** [comment]
@matthiasbosc Merci, je t'ai envoyé un mail.

**Comment by matthiasbosc** [comment]
@LuffyyyffuL Petite coquille désolé -> matthias (at) bosc (dot) io :+1:

**Comment by Finch29** [comment]
des nouvelles ? Car je voudrais bien utiliser mais je suis bloqué par le même souci ^^

**Comment by matthiasbosc** [comment]
Oui, désolé de ne pas avoir répondu plus tôt. La prochaine version réglera ça!
Je pense pouvoir la publier avant noel, il y aura aussi d'autres améliorations (multi-seedbox, support complet de Syno, téléchargement en local pour rTorrent, etc etc. :))

**Comment by matthiasbosc** [comment]
Cela a été un peu plus long que prévu, mais voilà, le commit [4606cc008898af952af37e0edc3122cb83fdc22e](https://github.com/matthiasbosc/t412/commit/4606cc008898af952af37e0edc3122cb83fdc22e) a résolu le souci! :)

**Comment by LuffyyyffuL** [comment]
Bonjour,

Merci pour ton retour.

Ma config nginx ressemble à ça :

 ##################
 ## HTTPS - T412 ##
 ##################

 location ^~ /t412 {
 root /var/www;
 access_log /var/log/nginx/NGINX_SITE_ACCESS--T412.log;
 error_log /var/log/nginx/NGINX_SITE_ERROR--T412.log;

 include /etc/nginx/conf.d/php.conf;
 include /etc/nginx/conf.d/cache.conf;
 index index.html index.php;
 try_files $uri $uri/ /index.php?$args; 
 }

J'ai bien récupéré tes dernières sources et complété le fichier "t411.class.php" :

 const API_URL = 'https://api.t411.li';
 const WEB_URL = 'https://t411.li';
 /** MySQL */
 const DB_HOST = 'localhost';
 const DB_NAME = 'DB_T412';
 const DB_USER = 't412';
 const DB_PASS = 'monmotdepasse';
 /** clé de sécurité - à récupérer sur setup.php */
 const KEY = "";
 /** préfixe pour DL Syno -- WIP */
 const DL_PREFIX = 'https://mondomaine/t412/';
 /** nom de domaine */
 public $domainName = 'mondomaine';
 /** utilisateur t411 */
 CONST T411USER = 'monusert411';
Mais quand je vais sur la page suivante, j'ai une erreur 500 :

https://mondomaine.fr/t412/setup.fr
Quelle configuration as-tu utilisée pour faire tes tests ?

Merci :)
29 décembre 2016 16:33 "Matthias BOSC"  a écrit:
	Cela a été un peu plus long que prévu, mais voilà, le commit 4606cc008898af952af37e0edc3122cb83fdc22e (https://github.com/matthiasbosc/t412/commit/4606cc008898af952af37e0edc3122cb83fdc22e) a résolu le souci! :)

**Comment by matthiasbosc** [comment]
Pense à inclure les logs de ton serveur web, sans cela je ne peux pas t'aider.
Aussi, supprime complètement le dossier t412 avant de le mettre à jour avec git pull.

**Comment by Finch29** [comment]
Merci @matthiasbosc pour ton taff ;) mais j'ai un autre soucis : https://i.imgur.com/xSYxCfU.png
Alors que j'ai fais copier/coller de la clé dans t412.class
Il arrive pas à crypter pour la BDD ... ;)
Log : https://i.imgur.com/GGjEU0Y.png

**Comment by matthiasbosc** [comment]
Oui je suis en train d'écrire sur mondedie à ce sujet.
Toute la compatibilité avec l'ancienne version est cassée.
Pour mettre à jour, **écrasez complètement les fichiers** et **supprimez l'ancienne BDD utilisée**.

**Comment by LuffyyyffuL** [comment]
Re,

1 - Le setup.php me dit que tout est OK

2 - J'ai bien la page d'authentification

3 - Dès que j'essai de me connecter, j'ai une erreur 500, voici mon log nginx error :

2016/12/29 17:39:46 [error] 13448#13448: *2273 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: Needs a 256-bit key! in /var/www/t412/utils.class.php:88
Stack trace:
#0 /var/www/t412/torrent.class.php(59): Utils->encrypt('usr_t411')
#1 /var/www/t412/login.php(7): Torrent->Auth('usr_t411', 'mp_t411', 1490805586)
#2 {main}
 thrown in /var/www/t412/utils.class.php on line 88" while reading response header from upstream, client: mon_ip_wan, server: mondomaine, request: "POST /t412/login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "mondomaine", referrer: "https://mondomaine/t412/login.php"
2016/12/29 17:40:03 [error] 13448#13448: *2272 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: Needs a 256-bit key! in /var/www/t412/utils.class.php:88
Stack trace:
#0 /var/www/t412/torrent.class.php(59): Utils->encrypt('usr_t411')
#1 /var/www/t412/login.php(7): Torrent->Auth('usr_t411', 'mp_t411', 1490805602)
#2 {main}
 thrown in /var/www/t412/utils.class.php on line 88" while reading response header from upstream, client: mon_ip_wan, server: mondomaine, request: "POST /t412/login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "mondomaine", referrer: "https://mondomaine/t412/login.php"
29 décembre 2016 17:31 "Matthias BOSC"  a écrit:
	Pense à inclure les logs de ton serveur web, sans cela je ne peux pas t'aider.
Aussi, supprime complètement le dossier t412 avant de le mettre à jour avec git pull.

**Comment by matthiasbosc** [comment]
Vérifie que tu possèdes l'extension mbstring, je viens de mettre à jour le
setup.php pour cela.

Le 29 décembre 2016 à 17:46, LuffyyyffuL <notifications@github.com> a écrit
:

**Comment by LuffyyyffuL** [comment]
Ma clé avait changée, je l'ai mise à jour et tout est OK.
Sinon, oui, j'ai bien l'extension :
	Version PHP: OKVérifications des extensions:
-- Extension curl: installée
-- Extension ctype: installée
-- Extension openssl: installée
-- Extension mbstring: installée
-- Extension pdo_mysql: installée
-- Extension xml: installée

Clé de chiffrement au mauvais format.
Veuillez utiliser une clé de 32 octets comme ci-dessous pour un chiffrement 256bits
4d5f5b9066d15567054f6702e6f5aed1e2cabcda68ce88ba52434e63f667181c

identifiants MySQL: insérés
-- Connexion MySQL: réussie
---- Création de la base de donnée: réussie
Pensez à ajouter les tâches cron nécessaires pour récupérer les tops, et pour le téléchargement automatique (facultatif).

	0 * * * * /usr/bin/php /var/www/t412/cli/top.php 0 * * * * /usr/bin/php /var/www/t412/cli/autodownload.php 

Merci beaucoup pour ton retour rapide, je vais tester t412 de suite :)
29 décembre 2016 17:51 "Matthias BOSC"  a écrit:
Vérifie que tu possèdes l'extension mbstring, je viens de mettre à jour le
setup.php pour cela.

Le 29 décembre 2016 à 17:46, LuffyyyffuL  a écrit
:

**Comment by matthiasbosc** [comment]
J'ai mis à jour le setup, et la manière de générer la clé. Peux-tu me confirmer que cela fonctionne ?

**Comment by Finch29** [comment]
Ton nouveau système de clé fonctionne parfaitement thx ;) !

**Comment by LuffyyyffuL** [comment]
C'est bon aussi pour moi.

Maintenant je rencontre un souci pour les TOPs. Log nginx error : 

`2016/12/29 18:14:26 [error] 18408#18408: *2618 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: NOPE. in /var/www/t412/user.class.php:243
Stack trace:
#0 /var/www/t412/top/today.php(4): User->getTopFromDB('top_day')
#1 {main}
  thrown in /var/www/t412/user.class.php on line 243" while reading response header from upstream, client: mon_ip_wan, server: mon_domaine, request: "GET /t412/top/today.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "mon_domaine", referrer: "https://mon_domaine/t412/index.php?search=iron+man&cat="
`

**Comment by matthiasbosc** [comment]
Réglé.
