### ISSUE TITLE
Triage dans la recherche

### ISSUE THREAD

**Issue by Finch29** [matthiasbosc/t412#5]
Le problème est tout "bête" :D  Quand je veux trier par date, seeder, leecher, ...

> 2016/12/29 18:33:22 [error] 4842#4842: *449 FastCGI sent in stderr: "PHP message: PHP Warning:  array_multisort(): Array sizes are inconsistent in /var/www/t412/t412.class.php on line 115" while sending to client, client: XXX.XXX.XXX.XXX, server: xxx.xxx, request: "GET /t412/index.php?search=Snowden&cat=&order=times_completed&type=desc HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "dl.breizhbox.eu", referrer: "https://xxx.xxx/t412/index.php?search=Snowden&cat=&order=size&type=desc"

**Comment by matthiasbosc** [comment]
Possible de m'indiquer ta config (version de php5, etc) ?

**Comment by Finch29** [comment]
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
nginx version: nginx/1.10.2
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

Après je sais pas ce que tu voudrais de plus ?

**Comment by matthiasbosc** [comment]
Problème réglé, merci du signalement.
Penses à mettre à jour les fichiers. :)

**Comment by Finch29** [comment]
Merci c'est nickel ;)
