### ISSUE TITLE
Petit règlages :D

### ISSUE THREAD

**Issue by Finch29** [matthiasbosc/t412#6]
1. Les images GIF stockées en local ne sont pas redirigé vers le sous-dossier
2. Quand je suis dans le Top Mois ou Semaine, tous les liens vont vers " http://domain.tld/t412/top/xxx " 
3. Quand je clique sur " Recherche " en dessous de la navbar : `<li><a href="/">Recherche</a></li>`
4. Dans " Mes séries ", dès que je veux supprimer une série, le lien de suppression est pas bon
5. J'ai une erreur récurrente dans mes logs : 

> 2016/12/30 19:44:01 [error] 7505#7505: *1012 open() "/var/www/t412/css/bootstrap.min.css.map" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: domain.tld, request: "GET /t412/css/bootstrap.min.css.map HTTP/1.1", host: "domain.tld"

Merci d'avance et bonne année ;)

**Comment by LuffyyyffuL** [comment]
Bonjour,

Je constate les mêmes soucis.

**Comment by Finch29** [comment]
Je vais paraître un peu chiant 😁 ajouter le " triage" dans les tops non ? 😊

**Comment by matthiasbosc** [comment]
@Finch29 Non ce ne sera pas ajouté. L'API renvoie les tops dans un ordre aléatoire, je suis obligé de les trier une fois par date et une seconde fois par catégories pour ensuite les segmenter en tableaux sur la page...
