### ISSUE TITLE
Erreur lors de l'envoi du torrent vers SeedBox type local

### ISSUE THREAD

**Issue by LuffyyyffuL** [matthiasbosc/t412#7]
Bonjour,

J'ai déclaré une SeedBox de type local, et lorsque je clique sur télécharger un torrent vers la Seedbox, j'ai l'erreur suivante : 

Erreur ! Impossible de télécharger le torrent (raison: Utilisateur non autorisé).

Une idée ?

Merci :)

**Comment by Finch29** [comment]
Hésite pas à drop ta base de données et deconnecte toi de l'interface. Refait une installation propre 😊

**Comment by LuffyyyffuL** [comment]
Je viens de tout réinstaller completement (suppression + reinstallation) et je rencontre encore le souci :/

**Comment by Finch29** [comment]
Tu t'es bien déconnecté ? Ou purgé les cookies

**Comment by LuffyyyffuL** [comment]
Je viens de tout refaire au propre et cette fois j'ai supprimé les cookies, mais toujours la même erreur :/

**Comment by Finch29** [comment]
Post tes log nginx ou apache 😀 il y a sûrement la solution 😊

**Comment by LuffyyyffuL** [comment]
Je n'ai pas grand chose, pas d'erreur.

Log nginx : 

XX.XX.XX.XX - antho [02/Jan/2017:11:49:23 +0100] "GET /t412/download.php?type=torrent&id=5580602&idserv=1 HTTP/1.1" 200 1217 "https://mon_domaine/t412/details.php?id=5580602" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

**Comment by matthiasbosc** [comment]
Tu as bien renseigné la variable ``T411USER`` dans le fichier ``t412.class.php`` ?

**Comment by LuffyyyffuL** [comment]
Oui :)

**Comment by matthiasbosc** [comment]
@LuffyyyffuL Peux-tu essayer en navigation privée (ce qui implique une reconnexion) ?
L'API de T411 générait des tokens invalides hier, ceci peut expliquer le problème.

**Comment by LuffyyyffuL** [comment]
@matthiasbosc Pareil :(

**Comment by matthiasbosc** [comment]
@LuffyyyffuL Peux-tu m'envoyer le contenu de ton fichier t412.class.php (sans les mots-de-passe) par mail ? matthias (at) bosc (dot) io

**Comment by matthiasbosc** [comment]
@LuffyyyffuL du nouveau ?

**Comment by LuffyyyffuL** [comment]
@matthiasbosc Je viens de t'envoyer mon fichier :)
