### ISSUE TITLE
Dès que je DL par t412 les torrents se mettent en pause

### ISSUE THREAD

**Issue by SckyzO** [matthiasbosc/t412#9]
Je ne sais pas pourquoi dès que je DL via t412 sur mon interface et que je l'envoie sur la seedbox les DL se mettent en pause. Soit avant d'avoir téléchargé soit après ...

**Comment by matthiasbosc** [comment]
Téléchargement sur Transmission ? Utilises-tu un dossier personnalisé ?

**Comment by SckyzO** [comment]
@matthiasbosc 
Oui je n'ai pas précisé dsl. 
Donc c'est une seedbox sur rtorrent/rutorrent. 
Mon dossier de réception des fichiers torrent est en 777
Le fichier torrent s'ajoute donc bien, mais se met en pose dès son lancement, ou parfois pour de petits fichiers ca télécharge et ça se met en pause ensuite.

**Comment by SckyzO** [comment]
Bonjour, 
le problème est réglé. 
Le problème venait de ma conf rtorrent : 
https://upandclear.org/2016/07/06/rutorrent-watchdir-torrents-en-pause/

Il suffit de commenter la ligne du fichier rtorrent.rc: 
#schedule = untied_directory,5,5,"stop_untied=/home/USER/torrents/WatchDir/*.torrent"

Merci
